# Subway Data Analysis

## Introduction

O sistema de ônibus e trens de Nova Iorque - o Metro Transit Authority - fornece seus dados para download através de  arquivos csv. Uma das informações disponíveis são os dados das catracas do metrô que contém logs semanais de entradas cumulativas e saídas por catraca por estação de metrô em algum intervalo de tempo.


Neste projeto iremos utilizar apenas os das catraca disponíveis em: http://web.mta.info/developers/turnstile.html.

# Sobre este projeto

Neste projeto você irá aplicar todos os conhecimentos adquiridos neste primeiro mês de curso. Iremos praticar tarefas básicas de aquisição, limpeza de dados e nesse processo iremos descobrir coisas essenciais sobre os dados utilizando o que foi aprendido no curso de estatística. 

O objetivo deste projeto é explorar a relação entre os dados das catracas do metro de Nova York e o clima no dia da coleta. Para isso, além dos dados do metrô, precisaremos os dados de clima da cidade de Nova York. 

Os principais pontos que serão verificados neste trabalho:

- Coleta de dados da internet
- Utilização de estatística para análise de dados
- Manipulação de dados e criação de gráficos simples com o `Pandas`

*Como conseguir ajuda*: Sugerimos que tente os seguintes canais, nas seguintes ordens:

| Tipo de dúvida\Canais         	| Google 	| Fórum 	| Slack 	| Email 	|
|-------------------------------	|--------	|-------	|-------	|-------	|
| Programação Pyhon e Pandas    	| 1      	| 2     	| 3     	|       	|
| Requisitos do projeto         	|        	| 1     	| 2     	| 3     	|
| Partes específicas do Projeto 	|        	| 1     	| 2     	| 3     	|

Os endereços dos canais são:

- Fórum: https://discussions.udacity.com/c/ndfdsi-project
- Slack: [udacity-br.slack.com](https://udacity-br.slack.com/messages/C5MT6E3E1)
- Email: data-suporte@udacity.com

**Espera-se que o estudante entregue este relatório com:**

- Todos os TODO feitos, pois eles são essenciais para que o código rode corretamente
- O arquivo ipynb exportado como html

Para entregar este projeto, vá a [sala de aula](https://coco.udacity.com/nanodegrees/nd111/locale/pt-br/versions/1.0.0/parts/339726/modules/339733/lessons/340886/project) e submeta o seu `.ipynb` e o html, zipados.

# Lembretes

Antes de começarmos, alguns lembretes devem ter em mente ao usar os notebooks iPython:

- Lembre-se de que você pode ver do lado esquerdo de uma célula de código quando foi executado pela última vez se houver um número dentro das chaves.
- Quando você inicia uma nova sessão do notebook, certifique-se de executar todas as células até o ponto em que você deixou a última vez. Mesmo que a saída ainda seja visível a partir de quando você executou as células em sua sessão anterior, o kernel começa em um estado novo, então você precisará recarregar os dados, etc. em uma nova sessão.
- O ponto anterior é útil para ter em mente se suas respostas não correspondem ao que é esperado nos questionários da aula. Tente recarregar os dados e execute todas as etapas de processamento um a um para garantir que você esteja trabalhando com as mesmas variáveis e dados que estão em cada fase do questionário.

## Seção 1 - Coleta de Dados

### *Exercicio 1.1*

Mãos a obra!! Agora é sua vez de coletar os dados. Escreva abaixo um código python que acesse o link http://web.mta.info/developers/turnstile.html e baixe os arquivos do mês de junho de 2017. O arquivo deverá ser salvo com o nome turnstile_170610.txt onde 17/06/10 é a data do arquivo.

Abaixo seguem alguns comandos que poderão te ajudar:

Utilize a biblioteca **urllib** para abrir e resgatar uma página da web. Utilize o comando abaixo onde **url** será o caminho da página da web onde se encontra o arquivo:

```python
u = urllib.urlopen(url)
html = u.read()
```

Utilize a biblioteca **BeautifulSoup** para procurar na página pelo link do arquivo que deseja baixar. Utilize o comando abaixo para criar o seu objeto *soup* e procurar por todas as tags 'a'no documento:
 
 
```python
soup = BeautifulSoup(html, "html.parser")
links = soup.find_all('a')
```

Uma dica para baixar apenas os arquivos do mês de junho é verificar a data no nome do arquivo. Por exemplo, para baixar o arquivo do dia 17/06/2017 verifique se o link termina com *"turnstile_170610.txt"*. Se não fizer isso você baixará todos os arquivos da página. Para fazer isso utilize o comando conforme abaixo:

```python
if not link['href'].endswith(x):
```

E a dica final é utilizar o comando abaixo para fazer o download do arquivo txt:

```python
urllib.urlretrieve(link_do_arquivo, filename)
```

Lembre-se, primeiro, carregue todos os pacotes e funções que você estará usando em sua análise.

In [17]:
# coding: utf-8

from urllib.request import urlopen, urlretrieve
from bs4 import BeautifulSoup

def recuperar_html(url):
    try:
        return str(urlopen(url).read())
    except Exception as e:
        print('Erro ao carregar url', e)

def recuperar_tag_a(html):
    soup = BeautifulSoup(html, "html.parser")
    return soup.find_all('a')

def filtrar_links(tags, filtro):
	values = []
	for t in tags:
		if t.get('href') and filtro in t.get('href'):
			values.append(t)
	
	return values

def recuperar_arquivos(url, tag):
	try:
		link = ''
		
		if not url.endswith('/'):
			link = url[:(url.rfind('/') + 1)] + tag.get('href')
		else:
			link = url + tag.get('href')
		
		filename = link[(link.rfind('/') + 1):]
		print('Recuperar arquivos {} para {}'.format(link, filename))
		req = urlretrieve(link, filename)
		
		return filename
		
	except Exception as e:
		print('Erro ao recuperar arquivos', e)
	
url = 'http://web.mta.info/developers/turnstile.html'
filtro = 'turnstile_1706'

tags = filtrar_links(recuperar_tag_a(recuperar_html(url)), filtro)
for t in tags:
	recuperar_arquivos(url, t)
    
print('fim')

Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170624.txt para turnstile_170624.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170617.txt para turnstile_170617.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170610.txt para turnstile_170610.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170603.txt para turnstile_170603.txt
fim

### *Exercicio 1.2*

Escreva uma função que pegue a lista de nomes dos arquivos que você baixou no exercicio 1.1 e consolide-os em um único arquivo. Deve existir apenas uma linha de cabeçalho no arquivo de saida. 

Por exemplo, se o arquivo_1 tiver:
linha 1...
linha 2...

e o outro arquivo, arquivo_2 tiver:
linha 3...
linha 4...
linha 5...

Devemos combinar o arquivo_1 com arquivo_2 em um arquivo mestre conforme abaixo:

'C/A, UNIT, SCP, DATEn, TIMEn, DESCn, ENTRIESn, EXITSn'
linha 1...
linha 2...
linha 3...
linha 4...
linha 5...

In [19]:
# coding: utf-8

import glob, os

def create_master_turnstile_file(filenames, output_file):
    try:
    	with open(output_file, 'w') as master_file:
    		master_file.write('C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn\n')
    		for filename in filenames:
    			with open(filename) as f:
    				next(f)
    					
    				for line in f:
    					data = line.strip().split(",")
    					ca,unit,scp,station,linename,division,date,time,desc,entries,exits = data
    					master_file.write('{},{},{},{},{},{},{},{}\n'.format(ca, unit, scp, date, time, desc, entries, exits))
    except Exception as e:
        print('Erro na escrita do arquivo', e)

output_file = 'turnstile_1706.txt'
filenames = []

os.chdir(".")
for file in glob.glob("*.txt"):
    filenames.append(file)
	
create_master_turnstile_file(filenames, output_file)

### *Exercicio 1.3*

Neste exercício, escreva um função que leia o master_file criado no exercicio anterior e carregue-o em um pandas dataframe. Esta função deve filtrar para que o dataframe possua apenas linhas onde a coluna "DESCn" possua o valor "Regular".

Por exemplo, se o data frame do pandas estiver conforme abaixo:
    
    ,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    1,A002,R051,02-00-00,05-01-11,04:00:00,DOOR,3144335,1088159
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    3,A002,R051,02-00-00,05-01-11,12:00:00,DOOR,3144424,1088231

O dataframe deverá ficar conforme abaixo depois de filtrar apenas as linhas onde a coluna DESCn possua o valor REGULAR:

    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177

In [1]:
# coding: utf-8

import numpy
import pandas
import pandasql

def filter_by_regular(filename):

    turnstile_data = pandas.read_csv(filename, encoding='ISO-8859-1')
    print(turnstile_data)
    q = """
    select * from turnstile_data where DESCn = 'REGULAR';
    """
    return pandasql.sqldf(q, locals())
	
output_file = 'turnstile_1706.txt'
a = filter_by_regular(output_file)
print(a)

          C/A  UNIT       SCP       DATEn     TIMEn    DESCn  ENTRIESn  \
0        A002  R051  02-00-00  05/27/2017  00:00:00  REGULAR   6195217
1        A002  R051  02-00-00  05/27/2017  04:00:00  REGULAR   6195240
2        A002  R051  02-00-00  05/27/2017  08:00:00  REGULAR   6195256
3        A002  R051  02-00-00  05/27/2017  12:00:00  REGULAR   6195346
4        A002  R051  02-00-00  05/27/2017  16:00:00  REGULAR   6195518
5        A002  R051  02-00-00  05/27/2017  20:00:00  REGULAR   6195765
6        A002  R051  02-00-00  05/28/2017  00:00:00  REGULAR   6195898
7        A002  R051  02-00-00  05/28/2017  04:00:00  REGULAR   6195914
8        A002  R051  02-00-00  05/28/2017  08:00:00  REGULAR   6195930
9        A002  R051  02-00-00  05/28/2017  12:00:00  REGULAR   6196024
10       A002  R051  02-00-00  05/28/2017  16:00:00  REGULAR   6196186
11       A002  R051  02-00-00  05/28/2017  20:00:00  REGULAR   6196446
12       A002  R051  02-00-00  05/29/2017  00:00:00  REGULAR   6196569
13       A002  R051  02-00-00  05/29/2017  04:00:00  REGULAR   6196587
14       A002  R051  02-00-00  05/29/2017  08:00:00  REGULAR   6196597
15       A002  R051  02-00-00  05/29/2017  12:00:00  REGULAR   6196666
16       A002  R051  02-00-00  05/29/2017  16:00:00  REGULAR   6196853
17       A002  R051  02-00-00  05/29/2017  20:00:00  REGULAR   6197107
18       A002  R051  02-00-00  05/30/2017  00:00:00  REGULAR   6197230
19       A002  R051  02-00-00  05/30/2017  04:00:00  REGULAR   6197238
20       A002  R051  02-00-00  05/30/2017  08:00:00  REGULAR   6197288
21       A002  R051  02-00-00  05/30/2017  12:00:00  REGULAR   6197470
22       A002  R051  02-00-00  05/30/2017  16:00:00  REGULAR   6197790
23       A002  R051  02-00-00  05/30/2017  20:00:00  REGULAR   6198624
24       A002  R051  02-00-00  05/31/2017  00:00:00  REGULAR   6198819
25       A002  R051  02-00-00  05/31/2017  04:00:00  REGULAR   6198834
26       A002  R051  02-00-00  05/31/2017  08:00:00  REGULAR   6198880
27       A002  R051  02-00-00  05/31/2017  12:00:00  REGULAR   6199053
28       A002  R051  02-00-00  05/31/2017  16:00:00  REGULAR   6199379
29       A002  R051  02-00-00  05/31/2017  20:00:00  REGULAR   6200200
...       ...   ...       ...         ...       ...      ...       ...
788184  TRAM2  R469  00-05-01  06/19/2017  01:00:00  REGULAR      5554
788185  TRAM2  R469  00-05-01  06/19/2017  05:00:00  REGULAR      5554
788186  TRAM2  R469  00-05-01  06/19/2017  09:00:00  REGULAR      5554
788187  TRAM2  R469  00-05-01  06/19/2017  13:00:00  REGULAR      5554
788188  TRAM2  R469  00-05-01  06/19/2017  17:00:00  REGULAR      5554
788189  TRAM2  R469  00-05-01  06/19/2017  21:00:00  REGULAR      5554
788190  TRAM2  R469  00-05-01  06/20/2017  01:00:00  REGULAR      5554
788191  TRAM2  R469  00-05-01  06/20/2017  05:00:00  REGULAR      5554
788192  TRAM2  R469  00-05-01  06/20/2017  09:00:00  REGULAR      5554
788193  TRAM2  R469  00-05-01  06/20/2017  13:00:00  REGULAR      5554
788194  TRAM2  R469  00-05-01  06/20/2017  17:00:00  REGULAR      5554
788195  TRAM2  R469  00-05-01  06/20/2017  21:00:00  REGULAR      5554
788196  TRAM2  R469  00-05-01  06/21/2017  01:00:00  REGULAR      5554
788197  TRAM2  R469  00-05-01  06/21/2017  05:00:00  REGULAR      5554
788198  TRAM2  R469  00-05-01  06/21/2017  09:00:00  REGULAR      5554
788199  TRAM2  R469  00-05-01  06/21/2017  13:00:00  REGULAR      5554
788200  TRAM2  R469  00-05-01  06/21/2017  17:00:00  REGULAR      5554
788201  TRAM2  R469  00-05-01  06/21/2017  21:00:00  REGULAR      5554
788202  TRAM2  R469  00-05-01  06/22/2017  01:00:00  REGULAR      5554
788203  TRAM2  R469  00-05-01  06/22/2017  05:00:00  REGULAR      5554
788204  TRAM2  R469  00-05-01  06/22/2017  09:00:00  REGULAR      5554
788205  TRAM2  R469  00-05-01  06/22/2017  13:00:00  REGULAR      5554
788206  TRAM2  R469  00-05-01  06/22/2017  17:00:00  REGULAR      5554
788207  TRAM2  R469  00-05-01  06/22/2017  21:00:00  REGULAR      5554
788208  TRAM2  R469  00-05-01  06/23/2017  01:00:00  REGULAR      5554
788209  TRAM2  R469  00-05-01  06/23/2017  05:00:00  REGULAR      5554
788210  TRAM2  R469  00-05-01  06/23/2017  09:00:00  REGULAR      5554
788211  TRAM2  R469  00-05-01  06/23/2017  13:00:00  REGULAR      5554
788212  TRAM2  R469  00-05-01  06/23/2017  17:00:00  REGULAR      5554
788213  TRAM2  R469  00-05-01  06/23/2017  21:00:00  REGULAR      5554

         EXITSn
0       2098317
1       2098318
2       2098347
3       2098432
4       2098491
5       2098537
6       2098559
7       2098562
8       2098581
9       2098646
10      2098685
11      2098723
12      2098745
13      2098747
14      2098766
15      2098845
16      2098891
17      2098922
18      2098946
19      2098949
20      2099066
21      2099345
22      2099442
23      2099521
24      2099552
25      2099555
26      2099671
27      2099950
28      2100021
29      2100072
...         ...
788184      301
788185      301
788186      301
788187      301
788188      301
788189      301
788190      301
788191      301
788192      301
788193      301
788194      301
788195      301
788196      301
788197      301
788198      301
788199      301
788200      301
788201      301
788202      301
788203      301
788204      301
788205      301
788206      301
788207      301
788208      301
788209      301
788210      301
788211      301
788212      301
788213      301

[788214 rows x 8 columns]
          C/A  UNIT       SCP       DATEn     TIMEn    DESCn  ENTRIESn  \
0        A002  R051  02-00-00  05/27/2017  00:00:00  REGULAR   6195217
1        A002  R051  02-00-00  05/27/2017  04:00:00  REGULAR   6195240
2        A002  R051  02-00-00  05/27/2017  08:00:00  REGULAR   6195256
3        A002  R051  02-00-00  05/27/2017  12:00:00  REGULAR   6195346
4        A002  R051  02-00-00  05/27/2017  16:00:00  REGULAR   6195518
5        A002  R051  02-00-00  05/27/2017  20:00:00  REGULAR   6195765
6        A002  R051  02-00-00  05/28/2017  00:00:00  REGULAR   6195898
7        A002  R051  02-00-00  05/28/2017  04:00:00  REGULAR   6195914
8        A002  R051  02-00-00  05/28/2017  08:00:00  REGULAR   6195930
9        A002  R051  02-00-00  05/28/2017  12:00:00  REGULAR   6196024
10       A002  R051  02-00-00  05/28/2017  16:00:00  REGULAR   6196186
11       A002  R051  02-00-00  05/28/2017  20:00:00  REGULAR   6196446
12       A002  R051  02-00-00  05/29/2017  00:00:00  REGULAR   6196569
13       A002  R051  02-00-00  05/29/2017  04:00:00  REGULAR   6196587
14       A002  R051  02-00-00  05/29/2017  08:00:00  REGULAR   6196597
15       A002  R051  02-00-00  05/29/2017  12:00:00  REGULAR   6196666
16       A002  R051  02-00-00  05/29/2017  16:00:00  REGULAR   6196853
17       A002  R051  02-00-00  05/29/2017  20:00:00  REGULAR   6197107
18       A002  R051  02-00-00  05/30/2017  00:00:00  REGULAR   6197230
19       A002  R051  02-00-00  05/30/2017  04:00:00  REGULAR   6197238
20       A002  R051  02-00-00  05/30/2017  08:00:00  REGULAR   6197288
21       A002  R051  02-00-00  05/30/2017  12:00:00  REGULAR   6197470
22       A002  R051  02-00-00  05/30/2017  16:00:00  REGULAR   6197790
23       A002  R051  02-00-00  05/30/2017  20:00:00  REGULAR   6198624
24       A002  R051  02-00-00  05/31/2017  00:00:00  REGULAR   6198819
25       A002  R051  02-00-00  05/31/2017  04:00:00  REGULAR   6198834
26       A002  R051  02-00-00  05/31/2017  08:00:00  REGULAR   6198880
27       A002  R051  02-00-00  05/31/2017  12:00:00  REGULAR   6199053
28       A002  R051  02-00-00  05/31/2017  16:00:00  REGULAR   6199379
29       A002  R051  02-00-00  05/31/2017  20:00:00  REGULAR   6200200
...       ...   ...       ...         ...       ...      ...       ...
785376  TRAM2  R469  00-05-01  06/19/2017  01:00:00  REGULAR      5554
785377  TRAM2  R469  00-05-01  06/19/2017  05:00:00  REGULAR      5554
785378  TRAM2  R469  00-05-01  06/19/2017  09:00:00  REGULAR      5554
785379  TRAM2  R469  00-05-01  06/19/2017  13:00:00  REGULAR      5554
785380  TRAM2  R469  00-05-01  06/19/2017  17:00:00  REGULAR      5554
785381  TRAM2  R469  00-05-01  06/19/2017  21:00:00  REGULAR      5554
785382  TRAM2  R469  00-05-01  06/20/2017  01:00:00  REGULAR      5554
785383  TRAM2  R469  00-05-01  06/20/2017  05:00:00  REGULAR      5554
785384  TRAM2  R469  00-05-01  06/20/2017  09:00:00  REGULAR      5554
785385  TRAM2  R469  00-05-01  06/20/2017  13:00:00  REGULAR      5554
785386  TRAM2  R469  00-05-01  06/20/2017  17:00:00  REGULAR      5554
785387  TRAM2  R469  00-05-01  06/20/2017  21:00:00  REGULAR      5554
785388  TRAM2  R469  00-05-01  06/21/2017  01:00:00  REGULAR      5554
785389  TRAM2  R469  00-05-01  06/21/2017  05:00:00  REGULAR      5554
785390  TRAM2  R469  00-05-01  06/21/2017  09:00:00  REGULAR      5554
785391  TRAM2  R469  00-05-01  06/21/2017  13:00:00  REGULAR      5554
785392  TRAM2  R469  00-05-01  06/21/2017  17:00:00  REGULAR      5554
785393  TRAM2  R469  00-05-01  06/21/2017  21:00:00  REGULAR      5554
785394  TRAM2  R469  00-05-01  06/22/2017  01:00:00  REGULAR      5554
785395  TRAM2  R469  00-05-01  06/22/2017  05:00:00  REGULAR      5554
785396  TRAM2  R469  00-05-01  06/22/2017  09:00:00  REGULAR      5554
785397  TRAM2  R469  00-05-01  06/22/2017  13:00:00  REGULAR      5554
785398  TRAM2  R469  00-05-01  06/22/2017  17:00:00  REGULAR      5554
785399  TRAM2  R469  00-05-01  06/22/2017  21:00:00  REGULAR      5554
785400  TRAM2  R469  00-05-01  06/23/2017  01:00:00  REGULAR      5554
785401  TRAM2  R469  00-05-01  06/23/2017  05:00:00  REGULAR      5554
785402  TRAM2  R469  00-05-01  06/23/2017  09:00:00  REGULAR      5554
785403  TRAM2  R469  00-05-01  06/23/2017  13:00:00  REGULAR      5554
785404  TRAM2  R469  00-05-01  06/23/2017  17:00:00  REGULAR      5554
785405  TRAM2  R469  00-05-01  06/23/2017  21:00:00  REGULAR      5554

         EXITSn
0       2098317
1       2098318
2       2098347
3       2098432
4       2098491
5       2098537
6       2098559
7       2098562
8       2098581
9       2098646
10      2098685
11      2098723
12      2098745
13      2098747
14      2098766
15      2098845
16      2098891
17      2098922
18      2098946
19      2098949
20      2099066
21      2099345
22      2099442
23      2099521
24      2099552
25      2099555
26      2099671
27      2099950
28      2100021
29      2100072
...         ...
785376      301
785377      301
785378      301
785379      301
785380      301
785381      301
785382      301
785383      301
785384      301
785385      301
785386      301
785387      301
785388      301
785389      301
785390      301
785391      301
785392      301
785393      301
785394      301
785395      301
785396      301
785397      301
785398      301
785399      301
785400      301
785401      301
785402      301
785403      301
785404      301
785405      301

[785406 rows x 8 columns]

### *Exercicio 1.4*


Os dados do metrô de NY possui dados cumulativos de entradas e saidas por linha. Assuma que você possui um dataframe chamado df que contém apenas linhas para uma catraca em particular (unico SCP, C/A, e UNIT). A função abaixo deve alterar essas entradas cumulativas para a contagem de entradas desde a última leitura (entradas desde a última linha do dataframe).

Mais especificamente, você deverá fazer duas coisas:

1 - Criar uma nova coluna chamada ENTRIESn_hourly
2 - Inserir nessa coluna a diferença enre ENTRIESn da coluna atual e a da coluna anterior. Se a linha possuir alguma NAN, preencha/substitua por 1.

Dica: as funções do pandas shift() e fillna() pode ser úteis nesse exercicio.

Abaixo tem um exemplo de como seu dataframe deve ficar ao final desse exercicio:

        C/A  UNIT       SCP     DATEn     TIMEn    DESCn  ENTRIESn    EXITSn  ENTRIESn_hourly
    0     A002  R051  02-00-00  05-01-11  00:00:00  REGULAR   3144312   1088151                1
    1     A002  R051  02-00-00  05-01-11  04:00:00  REGULAR   3144335   1088159               23
    2     A002  R051  02-00-00  05-01-11  08:00:00  REGULAR   3144353   1088177               18
    3     A002  R051  02-00-00  05-01-11  12:00:00  REGULAR   3144424   1088231               71
    4     A002  R051  02-00-00  05-01-11  16:00:00  REGULAR   3144594   1088275              170
    5     A002  R051  02-00-00  05-01-11  20:00:00  REGULAR   3144808   1088317              214
    6     A002  R051  02-00-00  05-02-11  00:00:00  REGULAR   3144895   1088328               87
    7     A002  R051  02-00-00  05-02-11  04:00:00  REGULAR   3144905   1088331               10
    8     A002  R051  02-00-00  05-02-11  08:00:00  REGULAR   3144941   1088420               36
    9     A002  R051  02-00-00  05-02-11  12:00:00  REGULAR   3145094   1088753              153
    10    A002  R051  02-00-00  05-02-11  16:00:00  REGULAR   3145337   1088823              243

In [ ]:
import pandas

def get_hourly_entries(df):
    
    
    #your code here
    return df

### *Exercicio 1.5*

Faça o mesmo do exercicio anterior mas agora considerando as saidas, coluna EXITSn.
Para isso crie uma coluna chamada de EXITSn_hourly e insira a diferença entre a coluna EXITSn da linha atual versus a linha anterior. Se tiver algum NaN, preencha/substitua por 0.

In [ ]:
import pandas

def get_hourly_exits(df):
    
    #your code here
    return df

### *Exercicio 1.6*

Dado uma variável de entrada que representa o tempo no formato de:
     "00:00:00" (hora: minutos: segundos)
    
Escreva uma função para extrair a parte da hora do tempo variável de entrada
E devolva-o como um número inteiro. Por exemplo:
         
         1) se a hora for 00, seu código deve retornar 0
         2) se a hora for 01, seu código deve retornar 1
         3) se a hora for 21, seu código deve retornar 21
        
Por favor, devolva a hora como um número inteiro.

In [ ]:
def time_to_hour(time):
    
    hour = # your code here
    return hour

## Exercicio 2 - Análise dos dados

### *Exercicio 2.1*

Para verificar a relação entre o movimento do metrô e o clima, precisaremos complementar os dados do arquivo já baixado com os dados do clima.
Nós complementamos para você este arquivo com os dados de clima de Nova Iorque  e disponibilizamos na área de materiais do projeto. Você pode acessa-lo pelo link: https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/turnstile_data_master_with_weather.csv

Agora que temos nossos dados em um arquivo csv, escreva um código python que leia este arquivo e salve-o em um data frame do pandas. 

Dica: 

Utilize o comando abaixo para ler o arquivo:

```python
pd.read_csv('output_list.txt', sep=",")
```

In [2]:
import pandas as pd

filename = "turnstile_data_master_with_weather.csv"


#your code here

### *Exercicio 2.2*

Agora crie uma função que calcule a quantidade de dias chuvosos, para isso retorne a contagem do numero de dias onde a coluna *"rain"* é igual a 1.

Dica: Você também pode achar que a interpretação de números como números inteiros ou float pode não
     funcionar inicialmente. Para contornar esta questão, pode ser útil converter
     esses números para números inteiros. Isso pode ser feito escrevendo cast (coluna como inteiro).
     Então, por exemplo, se queríamos lançar a coluna maxtempi como um número inteiro, nós devemos
     escrever algo como cast (maxtempi as integer) = 76, em oposição a simplesmente
     onde maxtempi = 76.

In [6]:

def num_rainy_days(df):

    


    #your code here
    return

### *Exercicio 2.3*

Calcule se estava nebuloso ou não (0 ou 1) e a temperatura máxima para fog (isto é, a temperatura máxima 
     para dias nebulosos e não nebuloso).

In [8]:

def max_temp_aggregate_by_fog(df):
    
    #your code here 
    return

### *Exercicio 2.4

Calcule agora a média de 'meantempi' nos dias que são sábado ou domingo (finais de semana):

In [ ]:
def avg_weekend_temperature(filename):
  
    mean_temp_weekends = 
    
    return mean_temp_weekends

### *Exercicio 2.5

Calcule a média da temperatura mínima 'mintempi' nos dias chuvosos onde da temperatura mínima foi maior que do 55 graus:

In [ ]:
def avg_min_temperature(filename):

    avg_min_temp_rainy = 
    
    return avg_min_temp_rainy

### *Exercicio 2.6

Antes de realizar qualquer análise, pode ser útil olhar para os dados que esperamos analisar. Mais especificamente, vamos examinR as entradas por hora em nossos dados do metrô de Nova York para determinar a distribuição dos dados. Estes dados são armazenados na coluna ['ENTRIESn_hourly'].
    
Trace dois histogramas nos mesmos eixos para mostrar as entradas quando esta chovendo vs quando não está chovendo. 
Abaixo está um exemplo sobre como traçar histogramas com pandas e matplotlib:
     
```python
Turnstile_weather ['column_to_graph']. Hist ()
```

In [ ]:
import numpy as np
import pandas
import matplotlib.pyplot as plt

def entries_histogram(turnstile_weather):
    
    
    
    plt.figure()
    turnstile_weather['...'] # your code here to plot a historgram for hourly entries when it is raining
    turnstile_weather['...'] # your code here to plot a histogram for hourly entries when it is not raining
    return plt

### *Exercicio 2.7

Os dados que acabou de plotar que tipo de ditribuição? Existe diferença na distribuição entre dias chuvosos e não chuvosos?

** Resposta **: Substitua este texto pela sua resposta!

### *Exercicio 2.8

Construa uma função que que retorne:

1. A média das entradas com chuva
2. A média das entradas sem chuva
3. O p-value comparando o numero com chuva e o número sem chuva

In [ ]:
import numpy as np
import scipy
import scipy.stats
import pandas

def mann_whitney_plus_means(turnstile_weather):
    
    
    ### YOUR CODE HERE ###
    
    return with_rain_mean, without_rain_mean, p # leave this line for the grader

Responda as perguntas abaixo de acordo com a saida das suas funções:

1. Qual a média das entradas com chuva?
2. Qual a média das entradas sem chuva?
3. Qual o p-value comparando os numeros com chuva e sem chuva?

** Resposta **: Substitua este texto pela sua resposta!

## Exercicio 3 - Map Reduce

### *Exercicio 3.1*

A entrada para esse exercício e o mesmo arquivo da seção anterior (Exercicio 2). Você pode baixar o arquivo neste link:

 https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/turnstile_data_master_with_weather.csv

Varmos criar um mapeador agora. Para cada linha de entrada, a saída do mapeador deve IMPRIMIR (não retornar) a UNIT como uma chave e o número de ENTRIESn_hourly como o valor. Separe a chave e o valor por uma guia. Por exemplo: 'R002 \ t105105.0'

In [ ]:
import sys

def mapper():
    

    for line in sys.stdin:
        # your code here


mapper()

### *Exercicio 3.2*

Agora crie o redutor. Dado o resultado do mapeador do exercicio anterior, o redutor deve imprimir(Não retornar) uma linha por UNIT, juntamente com o número total de ENTRIESn_hourly.Ao longo de maio (que é a duração dos nossos dados), separados por uma guia. Um exemplo de linha de saída do redutor pode ser assim: 'R001 \ t500625.0'

Você pode assumir que a entrada para o redutor está ordenada de tal forma que todas as linhas correspondentes a uma unidade particular são agrupados.

In [ ]:
def reducer():
    

    for line in sys.stdin:
        # your code here

        
reducer()