# Subway Data Analysis

## Introduction

O sistema de ônibus e trens de Nova Iorque - o Metro Transit Authority - fornece seus dados para download através de  arquivos csv. Uma das informações disponíveis são os dados das catracas do metrô que contém logs semanais de entradas cumulativas e saídas por catraca por estação de metrô em algum intervalo de tempo.


Neste projeto iremos utilizar apenas os das catraca disponíveis em: http://web.mta.info/developers/turnstile.html.

# Sobre este projeto

Neste projeto você irá aplicar todos os conhecimentos adquiridos neste primeiro mês de curso. Iremos praticar tarefas básicas de aquisição, limpeza de dados e nesse processo iremos descobrir coisas essenciais sobre os dados utilizando o que foi aprendido no curso de estatística. 

O objetivo deste projeto é explorar a relação entre os dados das catracas do metro de Nova York e o clima no dia da coleta. Para isso, além dos dados do metrô, precisaremos os dados de clima da cidade de Nova York. 

Os principais pontos que serão verificados neste trabalho:

- Coleta de dados da internet
- Utilização de estatística para análise de dados
- Manipulação de dados e criação de gráficos simples com o `Pandas`

*Como conseguir ajuda*: Sugerimos que tente os seguintes canais, nas seguintes ordens:

| Tipo de dúvida\Canais         	| Google 	| Fórum 	| Slack 	| Email 	|
|-------------------------------	|--------	|-------	|-------	|-------	|
| Programação Pyhon e Pandas    	| 1      	| 2     	| 3     	|       	|
| Requisitos do projeto         	|        	| 1     	| 2     	| 3     	|
| Partes específicas do Projeto 	|        	| 1     	| 2     	| 3     	|

Os endereços dos canais são:

- Fórum: https://discussions.udacity.com/c/ndfdsi-project
- Slack: [udacity-br.slack.com](https://udacity-br.slack.com/messages/C5MT6E3E1)
- Email: data-suporte@udacity.com

**Espera-se que o estudante entregue este relatório com:**

- Todos os TODO feitos, pois eles são essenciais para que o código rode corretamente
- O arquivo ipynb exportado como html

Para entregar este projeto, vá a [sala de aula](https://coco.udacity.com/nanodegrees/nd111/locale/pt-br/versions/1.0.0/parts/339726/modules/339733/lessons/340886/project) e submeta o seu `.ipynb` e o html, zipados.

# Lembretes

Antes de começarmos, alguns lembretes devem ter em mente ao usar os notebooks iPython:

- Lembre-se de que você pode ver do lado esquerdo de uma célula de código quando foi executado pela última vez se houver um número dentro das chaves.
- Quando você inicia uma nova sessão do notebook, certifique-se de executar todas as células até o ponto em que você deixou a última vez. Mesmo que a saída ainda seja visível a partir de quando você executou as células em sua sessão anterior, o kernel começa em um estado novo, então você precisará recarregar os dados, etc. em uma nova sessão.
- O ponto anterior é útil para ter em mente se suas respostas não correspondem ao que é esperado nos questionários da aula. Tente recarregar os dados e execute todas as etapas de processamento um a um para garantir que você esteja trabalhando com as mesmas variáveis e dados que estão em cada fase do questionário.

## Seção 1 - Coleta de Dados

### *Exercicio 1.1*

Mãos a obra!! Agora é sua vez de coletar os dados. Escreva abaixo um código python que acesse o link http://web.mta.info/developers/turnstile.html e baixe os arquivos do mês de junho de 2017. O arquivo deverá ser salvo com o nome turnstile_170610.txt onde 17/06/10 é a data do arquivo.

Abaixo seguem alguns comandos que poderão te ajudar:

Utilize a biblioteca **urllib** para abrir e resgatar uma página da web. Utilize o comando abaixo onde **url** será o caminho da página da web onde se encontra o arquivo:

```python
u = urllib.urlopen(url)
html = u.read()
```

Utilize a biblioteca **BeautifulSoup** para procurar na página pelo link do arquivo que deseja baixar. Utilize o comando abaixo para criar o seu objeto *soup* e procurar por todas as tags 'a'no documento:
 
 
```python
soup = BeautifulSoup(html, "html.parser")
links = soup.find_all('a')
```

Uma dica para baixar apenas os arquivos do mês de junho é verificar a data no nome do arquivo. Por exemplo, para baixar o arquivo do dia 17/06/2017 verifique se o link termina com *"turnstile_170610.txt"*. Se não fizer isso você baixará todos os arquivos da página. Para fazer isso utilize o comando conforme abaixo:

```python
if not link['href'].endswith(x):
```

E a dica final é utilizar o comando abaixo para fazer o download do arquivo txt:

```python
urllib.urlretrieve(link_do_arquivo, filename)
```

Lembre-se, primeiro, carregue todos os pacotes e funções que você estará usando em sua análise.

In [17]:
# coding: utf-8

from urllib.request import urlopen, urlretrieve
from bs4 import BeautifulSoup

def recuperar_html(url):
    try:
        return str(urlopen(url).read())
    except Exception as e:
        print('Erro ao carregar url', e)

def recuperar_tag_a(html):
    soup = BeautifulSoup(html, "html.parser")
    return soup.find_all('a')

def filtrar_links(tags, filtro):
	values = []
	for t in tags:
		if t.get('href') and filtro in t.get('href'):
			values.append(t)
	
	return values

def recuperar_arquivos(url, tag):
	try:
		link = ''
		
		if not url.endswith('/'):
			link = url[:(url.rfind('/') + 1)] + tag.get('href')
		else:
			link = url + tag.get('href')
		
		filename = link[(link.rfind('/') + 1):]
		print('Recuperar arquivos {} para {}'.format(link, filename))
		req = urlretrieve(link, filename)
		
		return filename
		
	except Exception as e:
		print('Erro ao recuperar arquivos', e)
	
url = 'http://web.mta.info/developers/turnstile.html'
filtro = 'turnstile_1706'

tags = filtrar_links(recuperar_tag_a(recuperar_html(url)), filtro)
for t in tags:
	recuperar_arquivos(url, t)
    
print('fim')

Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170624.txt para turnstile_170624.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170617.txt para turnstile_170617.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170610.txt para turnstile_170610.txt
Recuperar arquivos http://web.mta.info/developers/data/nyct/turnstile/turnstile_170603.txt para turnstile_170603.txt
fim

### *Exercicio 1.2*

Escreva uma função que pegue a lista de nomes dos arquivos que você baixou no exercicio 1.1 e consolide-os em um único arquivo. Deve existir apenas uma linha de cabeçalho no arquivo de saida. 

Por exemplo, se o arquivo_1 tiver:
linha 1...
linha 2...

e o outro arquivo, arquivo_2 tiver:
linha 3...
linha 4...
linha 5...

Devemos combinar o arquivo_1 com arquivo_2 em um arquivo mestre conforme abaixo:

'C/A, UNIT, SCP, DATEn, TIMEn, DESCn, ENTRIESn, EXITSn'
linha 1...
linha 2...
linha 3...
linha 4...
linha 5...

In [19]:
# coding: utf-8

import glob, os

def create_master_turnstile_file(filenames, output_file):
    try:
    	with open(output_file, 'w') as master_file:
    		master_file.write('C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn\n')
    		for filename in filenames:
    			with open(filename) as f:
    				next(f)
    					
    				for line in f:
    					data = line.strip().split(",")
    					ca,unit,scp,station,linename,division,date,time,desc,entries,exits = data
    					master_file.write('{},{},{},{},{},{},{},{}\n'.format(ca, unit, scp, date, time, desc, entries, exits))
    except Exception as e:
        print('Erro na escrita do arquivo', e)

output_file = 'turnstile_1706.txt'
filenames = []

os.chdir(".")
for file in glob.glob("*.txt"):
    filenames.append(file)
	
create_master_turnstile_file(filenames, output_file)

### *Exercicio 1.3*

Neste exercício, escreva um função que leia o master_file criado no exercicio anterior e carregue-o em um pandas dataframe. Esta função deve filtrar para que o dataframe possua apenas linhas onde a coluna "DESCn" possua o valor "Regular".

Por exemplo, se o data frame do pandas estiver conforme abaixo:
    
    ,C/A,UNIT,SCP,DATEn,TIMEn,DESCn,ENTRIESn,EXITSn
    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    1,A002,R051,02-00-00,05-01-11,04:00:00,DOOR,3144335,1088159
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177
    3,A002,R051,02-00-00,05-01-11,12:00:00,DOOR,3144424,1088231

O dataframe deverá ficar conforme abaixo depois de filtrar apenas as linhas onde a coluna DESCn possua o valor REGULAR:

    0,A002,R051,02-00-00,05-01-11,00:00:00,REGULAR,3144312,1088151
    2,A002,R051,02-00-00,05-01-11,08:00:00,REGULAR,3144353,1088177

In [2]:
# coding: utf-8

import numpy
import pandas
import pandasql

def filter_by_regular(filename):

    turnstile_data = pandas.read_csv(filename, encoding='ISO-8859-1')
    q = """
    select * from turnstile_data where DESCn = 'REGULAR';
    """
    return pandasql.sqldf(q, locals())
	
output_file = 'turnstile_1706.txt'
a = filter_by_regular(output_file)
print(a)

          C/A  UNIT       SCP       DATEn     TIMEn    DESCn  ENTRIESn  \
0        A002  R051  02-00-00  05/27/2017  00:00:00  REGULAR   6195217
1        A002  R051  02-00-00  05/27/2017  04:00:00  REGULAR   6195240
2        A002  R051  02-00-00  05/27/2017  08:00:00  REGULAR   6195256
3        A002  R051  02-00-00  05/27/2017  12:00:00  REGULAR   6195346
4        A002  R051  02-00-00  05/27/2017  16:00:00  REGULAR   6195518
5        A002  R051  02-00-00  05/27/2017  20:00:00  REGULAR   6195765
6        A002  R051  02-00-00  05/28/2017  00:00:00  REGULAR   6195898
7        A002  R051  02-00-00  05/28/2017  04:00:00  REGULAR   6195914
8        A002  R051  02-00-00  05/28/2017  08:00:00  REGULAR   6195930
9        A002  R051  02-00-00  05/28/2017  12:00:00  REGULAR   6196024
10       A002  R051  02-00-00  05/28/2017  16:00:00  REGULAR   6196186
11       A002  R051  02-00-00  05/28/2017  20:00:00  REGULAR   6196446
12       A002  R051  02-00-00  05/29/2017  00:00:00  REGULAR   6196569
13       A002  R051  02-00-00  05/29/2017  04:00:00  REGULAR   6196587
14       A002  R051  02-00-00  05/29/2017  08:00:00  REGULAR   6196597
15       A002  R051  02-00-00  05/29/2017  12:00:00  REGULAR   6196666
16       A002  R051  02-00-00  05/29/2017  16:00:00  REGULAR   6196853
17       A002  R051  02-00-00  05/29/2017  20:00:00  REGULAR   6197107
18       A002  R051  02-00-00  05/30/2017  00:00:00  REGULAR   6197230
19       A002  R051  02-00-00  05/30/2017  04:00:00  REGULAR   6197238
20       A002  R051  02-00-00  05/30/2017  08:00:00  REGULAR   6197288
21       A002  R051  02-00-00  05/30/2017  12:00:00  REGULAR   6197470
22       A002  R051  02-00-00  05/30/2017  16:00:00  REGULAR   6197790
23       A002  R051  02-00-00  05/30/2017  20:00:00  REGULAR   6198624
24       A002  R051  02-00-00  05/31/2017  00:00:00  REGULAR   6198819
25       A002  R051  02-00-00  05/31/2017  04:00:00  REGULAR   6198834
26       A002  R051  02-00-00  05/31/2017  08:00:00  REGULAR   6198880
27       A002  R051  02-00-00  05/31/2017  12:00:00  REGULAR   6199053
28       A002  R051  02-00-00  05/31/2017  16:00:00  REGULAR   6199379
29       A002  R051  02-00-00  05/31/2017  20:00:00  REGULAR   6200200
...       ...   ...       ...         ...       ...      ...       ...
785376  TRAM2  R469  00-05-01  06/19/2017  01:00:00  REGULAR      5554
785377  TRAM2  R469  00-05-01  06/19/2017  05:00:00  REGULAR      5554
785378  TRAM2  R469  00-05-01  06/19/2017  09:00:00  REGULAR      5554
785379  TRAM2  R469  00-05-01  06/19/2017  13:00:00  REGULAR      5554
785380  TRAM2  R469  00-05-01  06/19/2017  17:00:00  REGULAR      5554
785381  TRAM2  R469  00-05-01  06/19/2017  21:00:00  REGULAR      5554
785382  TRAM2  R469  00-05-01  06/20/2017  01:00:00  REGULAR      5554
785383  TRAM2  R469  00-05-01  06/20/2017  05:00:00  REGULAR      5554
785384  TRAM2  R469  00-05-01  06/20/2017  09:00:00  REGULAR      5554
785385  TRAM2  R469  00-05-01  06/20/2017  13:00:00  REGULAR      5554
785386  TRAM2  R469  00-05-01  06/20/2017  17:00:00  REGULAR      5554
785387  TRAM2  R469  00-05-01  06/20/2017  21:00:00  REGULAR      5554
785388  TRAM2  R469  00-05-01  06/21/2017  01:00:00  REGULAR      5554
785389  TRAM2  R469  00-05-01  06/21/2017  05:00:00  REGULAR      5554
785390  TRAM2  R469  00-05-01  06/21/2017  09:00:00  REGULAR      5554
785391  TRAM2  R469  00-05-01  06/21/2017  13:00:00  REGULAR      5554
785392  TRAM2  R469  00-05-01  06/21/2017  17:00:00  REGULAR      5554
785393  TRAM2  R469  00-05-01  06/21/2017  21:00:00  REGULAR      5554
785394  TRAM2  R469  00-05-01  06/22/2017  01:00:00  REGULAR      5554
785395  TRAM2  R469  00-05-01  06/22/2017  05:00:00  REGULAR      5554
785396  TRAM2  R469  00-05-01  06/22/2017  09:00:00  REGULAR      5554
785397  TRAM2  R469  00-05-01  06/22/2017  13:00:00  REGULAR      5554
785398  TRAM2  R469  00-05-01  06/22/2017  17:00:00  REGULAR      5554
785399  TRAM2  R469  00-05-01  06/22/2017  21:00:00  REGULAR      5554
785400  TRAM2  R469  00-05-01  06/23/2017  01:00:00  REGULAR      5554
785401  TRAM2  R469  00-05-01  06/23/2017  05:00:00  REGULAR      5554
785402  TRAM2  R469  00-05-01  06/23/2017  09:00:00  REGULAR      5554
785403  TRAM2  R469  00-05-01  06/23/2017  13:00:00  REGULAR      5554
785404  TRAM2  R469  00-05-01  06/23/2017  17:00:00  REGULAR      5554
785405  TRAM2  R469  00-05-01  06/23/2017  21:00:00  REGULAR      5554

         EXITSn
0       2098317
1       2098318
2       2098347
3       2098432
4       2098491
5       2098537
6       2098559
7       2098562
8       2098581
9       2098646
10      2098685
11      2098723
12      2098745
13      2098747
14      2098766
15      2098845
16      2098891
17      2098922
18      2098946
19      2098949
20      2099066
21      2099345
22      2099442
23      2099521
24      2099552
25      2099555
26      2099671
27      2099950
28      2100021
29      2100072
...         ...
785376      301
785377      301
785378      301
785379      301
785380      301
785381      301
785382      301
785383      301
785384      301
785385      301
785386      301
785387      301
785388      301
785389      301
785390      301
785391      301
785392      301
785393      301
785394      301
785395      301
785396      301
785397      301
785398      301
785399      301
785400      301
785401      301
785402      301
785403      301
785404      301
785405      301

[785406 rows x 8 columns]

### *Exercicio 1.4*


Os dados do metrô de NY possui dados cumulativos de entradas e saidas por linha. Assuma que você possui um dataframe chamado df que contém apenas linhas para uma catraca em particular (unico SCP, C/A, e UNIT). A função abaixo deve alterar essas entradas cumulativas para a contagem de entradas desde a última leitura (entradas desde a última linha do dataframe).

Mais especificamente, você deverá fazer duas coisas:

1 - Criar uma nova coluna chamada ENTRIESn_hourly
2 - Inserir nessa coluna a diferença enre ENTRIESn da coluna atual e a da coluna anterior. Se a linha possuir alguma NAN, preencha/substitua por 1.

Dica: as funções do pandas shift() e fillna() pode ser úteis nesse exercicio.

Abaixo tem um exemplo de como seu dataframe deve ficar ao final desse exercicio:

        C/A  UNIT       SCP     DATEn     TIMEn    DESCn  ENTRIESn    EXITSn  ENTRIESn_hourly
    0     A002  R051  02-00-00  05-01-11  00:00:00  REGULAR   3144312   1088151                1
    1     A002  R051  02-00-00  05-01-11  04:00:00  REGULAR   3144335   1088159               23
    2     A002  R051  02-00-00  05-01-11  08:00:00  REGULAR   3144353   1088177               18
    3     A002  R051  02-00-00  05-01-11  12:00:00  REGULAR   3144424   1088231               71
    4     A002  R051  02-00-00  05-01-11  16:00:00  REGULAR   3144594   1088275              170
    5     A002  R051  02-00-00  05-01-11  20:00:00  REGULAR   3144808   1088317              214
    6     A002  R051  02-00-00  05-02-11  00:00:00  REGULAR   3144895   1088328               87
    7     A002  R051  02-00-00  05-02-11  04:00:00  REGULAR   3144905   1088331               10
    8     A002  R051  02-00-00  05-02-11  08:00:00  REGULAR   3144941   1088420               36
    9     A002  R051  02-00-00  05-02-11  12:00:00  REGULAR   3145094   1088753              153
    10    A002  R051  02-00-00  05-02-11  16:00:00  REGULAR   3145337   1088823              243

In [3]:
# coding: utf-8

import numpy
import pandas
import pandasql

def filter_by_regular(filename):

    turnstile_data = pandas.read_csv(filename, encoding='ISO-8859-1')
    q = """
    select * from turnstile_data where DESCn = 'REGULAR';
    """
    return pandasql.sqldf(q, locals())
	
def get_hourly_entries(df):
    #Responsável por pegar o atual - o anterior com shift(1)
    df['ENTRIESn_hourly'] = pandas.Series(df['ENTRIESn'] - df['ENTRIESn'].shift(1))
    # Função que tira NaN e modifica para 1
    df['ENTRIESn_hourly'] = df['ENTRIESn_hourly'].fillna(1) 
    return df

output_file = 'turnstile_1706.txt'
print(get_hourly_entries(filter_by_regular(output_file)))

          C/A  UNIT       SCP       DATEn     TIMEn    DESCn  ENTRIESn  \
0        A002  R051  02-00-00  05/27/2017  00:00:00  REGULAR   6195217
1        A002  R051  02-00-00  05/27/2017  04:00:00  REGULAR   6195240
2        A002  R051  02-00-00  05/27/2017  08:00:00  REGULAR   6195256
3        A002  R051  02-00-00  05/27/2017  12:00:00  REGULAR   6195346
4        A002  R051  02-00-00  05/27/2017  16:00:00  REGULAR   6195518
5        A002  R051  02-00-00  05/27/2017  20:00:00  REGULAR   6195765
6        A002  R051  02-00-00  05/28/2017  00:00:00  REGULAR   6195898
7        A002  R051  02-00-00  05/28/2017  04:00:00  REGULAR   6195914
8        A002  R051  02-00-00  05/28/2017  08:00:00  REGULAR   6195930
9        A002  R051  02-00-00  05/28/2017  12:00:00  REGULAR   6196024
10       A002  R051  02-00-00  05/28/2017  16:00:00  REGULAR   6196186
11       A002  R051  02-00-00  05/28/2017  20:00:00  REGULAR   6196446
12       A002  R051  02-00-00  05/29/2017  00:00:00  REGULAR   6196569
13       A002  R051  02-00-00  05/29/2017  04:00:00  REGULAR   6196587
14       A002  R051  02-00-00  05/29/2017  08:00:00  REGULAR   6196597
15       A002  R051  02-00-00  05/29/2017  12:00:00  REGULAR   6196666
16       A002  R051  02-00-00  05/29/2017  16:00:00  REGULAR   6196853
17       A002  R051  02-00-00  05/29/2017  20:00:00  REGULAR   6197107
18       A002  R051  02-00-00  05/30/2017  00:00:00  REGULAR   6197230
19       A002  R051  02-00-00  05/30/2017  04:00:00  REGULAR   6197238
20       A002  R051  02-00-00  05/30/2017  08:00:00  REGULAR   6197288
21       A002  R051  02-00-00  05/30/2017  12:00:00  REGULAR   6197470
22       A002  R051  02-00-00  05/30/2017  16:00:00  REGULAR   6197790
23       A002  R051  02-00-00  05/30/2017  20:00:00  REGULAR   6198624
24       A002  R051  02-00-00  05/31/2017  00:00:00  REGULAR   6198819
25       A002  R051  02-00-00  05/31/2017  04:00:00  REGULAR   6198834
26       A002  R051  02-00-00  05/31/2017  08:00:00  REGULAR   6198880
27       A002  R051  02-00-00  05/31/2017  12:00:00  REGULAR   6199053
28       A002  R051  02-00-00  05/31/2017  16:00:00  REGULAR   6199379
29       A002  R051  02-00-00  05/31/2017  20:00:00  REGULAR   6200200
...       ...   ...       ...         ...       ...      ...       ...
785376  TRAM2  R469  00-05-01  06/19/2017  01:00:00  REGULAR      5554
785377  TRAM2  R469  00-05-01  06/19/2017  05:00:00  REGULAR      5554
785378  TRAM2  R469  00-05-01  06/19/2017  09:00:00  REGULAR      5554
785379  TRAM2  R469  00-05-01  06/19/2017  13:00:00  REGULAR      5554
785380  TRAM2  R469  00-05-01  06/19/2017  17:00:00  REGULAR      5554
785381  TRAM2  R469  00-05-01  06/19/2017  21:00:00  REGULAR      5554
785382  TRAM2  R469  00-05-01  06/20/2017  01:00:00  REGULAR      5554
785383  TRAM2  R469  00-05-01  06/20/2017  05:00:00  REGULAR      5554
785384  TRAM2  R469  00-05-01  06/20/2017  09:00:00  REGULAR      5554
785385  TRAM2  R469  00-05-01  06/20/2017  13:00:00  REGULAR      5554
785386  TRAM2  R469  00-05-01  06/20/2017  17:00:00  REGULAR      5554
785387  TRAM2  R469  00-05-01  06/20/2017  21:00:00  REGULAR      5554
785388  TRAM2  R469  00-05-01  06/21/2017  01:00:00  REGULAR      5554
785389  TRAM2  R469  00-05-01  06/21/2017  05:00:00  REGULAR      5554
785390  TRAM2  R469  00-05-01  06/21/2017  09:00:00  REGULAR      5554
785391  TRAM2  R469  00-05-01  06/21/2017  13:00:00  REGULAR      5554
785392  TRAM2  R469  00-05-01  06/21/2017  17:00:00  REGULAR      5554
785393  TRAM2  R469  00-05-01  06/21/2017  21:00:00  REGULAR      5554
785394  TRAM2  R469  00-05-01  06/22/2017  01:00:00  REGULAR      5554
785395  TRAM2  R469  00-05-01  06/22/2017  05:00:00  REGULAR      5554
785396  TRAM2  R469  00-05-01  06/22/2017  09:00:00  REGULAR      5554
785397  TRAM2  R469  00-05-01  06/22/2017  13:00:00  REGULAR      5554
785398  TRAM2  R469  00-05-01  06/22/2017  17:00:00  REGULAR      5554
785399  TRAM2  R469  00-05-01  06/22/2017  21:00:00  REGULAR      5554
785400  TRAM2  R469  00-05-01  06/23/2017  01:00:00  REGULAR      5554
785401  TRAM2  R469  00-05-01  06/23/2017  05:00:00  REGULAR      5554
785402  TRAM2  R469  00-05-01  06/23/2017  09:00:00  REGULAR      5554
785403  TRAM2  R469  00-05-01  06/23/2017  13:00:00  REGULAR      5554
785404  TRAM2  R469  00-05-01  06/23/2017  17:00:00  REGULAR      5554
785405  TRAM2  R469  00-05-01  06/23/2017  21:00:00  REGULAR      5554

         EXITSn  ENTRIESn_hourly
0       2098317              1.0
1       2098318             23.0
2       2098347             16.0
3       2098432             90.0
4       2098491            172.0
5       2098537            247.0
6       2098559            133.0
7       2098562             16.0
8       2098581             16.0
9       2098646             94.0
10      2098685            162.0
11      2098723            260.0
12      2098745            123.0
13      2098747             18.0
14      2098766             10.0
15      2098845             69.0
16      2098891            187.0
17      2098922            254.0
18      2098946            123.0
19      2098949              8.0
20      2099066             50.0
21      2099345            182.0
22      2099442            320.0
23      2099521            834.0
24      2099552            195.0
25      2099555             15.0
26      2099671             46.0
27      2099950            173.0
28      2100021            326.0
29      2100072            821.0
...         ...              ...
785376      301              0.0
785377      301              0.0
785378      301              0.0
785379      301              0.0
785380      301              0.0
785381      301              0.0
785382      301              0.0
785383      301              0.0
785384      301              0.0
785385      301              0.0
785386      301              0.0
785387      301              0.0
785388      301              0.0
785389      301              0.0
785390      301              0.0
785391      301              0.0
785392      301              0.0
785393      301              0.0
785394      301              0.0
785395      301              0.0
785396      301              0.0
785397      301              0.0
785398      301              0.0
785399      301              0.0
785400      301              0.0
785401      301              0.0
785402      301              0.0
785403      301              0.0
785404      301              0.0
785405      301              0.0

[785406 rows x 9 columns]

### *Exercicio 1.5*

Faça o mesmo do exercicio anterior mas agora considerando as saidas, coluna EXITSn.
Para isso crie uma coluna chamada de EXITSn_hourly e insira a diferença entre a coluna EXITSn da linha atual versus a linha anterior. Se tiver algum NaN, preencha/substitua por 0.

In [4]:
# coding: utf-8

import numpy
import pandas
import pandasql

def filter_by_regular(filename):

    turnstile_data = pandas.read_csv(filename, encoding='ISO-8859-1')
    q = """
    select * from turnstile_data where DESCn = 'REGULAR';
    """
    return pandasql.sqldf(q, locals())

def get_hourly_entries(df):
    #Responsável por pegar o atual - o anterior com shift(1)
    df['ENTRIESn_hourly'] = pandas.Series(df['ENTRIESn'] - df['ENTRIESn'].shift(1))
    # Função que tira NaN e modifica para 1
    df['ENTRIESn_hourly'] = df['ENTRIESn_hourly'].fillna(1) 
    return df

def get_hourly_exits(df):
    df['EXITSn_hourly'] = pandas.Series(df['EXITSn'] - df['EXITSn'].shift(1))
    df['EXITSn_hourly'] = df['EXITSn_hourly'].fillna(1) 
    return df

output_file = 'turnstile_1706.txt'
print(get_hourly_exits(get_hourly_entries(filter_by_regular(output_file))))

          C/A  UNIT       SCP       DATEn     TIMEn    DESCn  ENTRIESn  \
0        A002  R051  02-00-00  05/27/2017  00:00:00  REGULAR   6195217
1        A002  R051  02-00-00  05/27/2017  04:00:00  REGULAR   6195240
2        A002  R051  02-00-00  05/27/2017  08:00:00  REGULAR   6195256
3        A002  R051  02-00-00  05/27/2017  12:00:00  REGULAR   6195346
4        A002  R051  02-00-00  05/27/2017  16:00:00  REGULAR   6195518
5        A002  R051  02-00-00  05/27/2017  20:00:00  REGULAR   6195765
6        A002  R051  02-00-00  05/28/2017  00:00:00  REGULAR   6195898
7        A002  R051  02-00-00  05/28/2017  04:00:00  REGULAR   6195914
8        A002  R051  02-00-00  05/28/2017  08:00:00  REGULAR   6195930
9        A002  R051  02-00-00  05/28/2017  12:00:00  REGULAR   6196024
10       A002  R051  02-00-00  05/28/2017  16:00:00  REGULAR   6196186
11       A002  R051  02-00-00  05/28/2017  20:00:00  REGULAR   6196446
12       A002  R051  02-00-00  05/29/2017  00:00:00  REGULAR   6196569
13       A002  R051  02-00-00  05/29/2017  04:00:00  REGULAR   6196587
14       A002  R051  02-00-00  05/29/2017  08:00:00  REGULAR   6196597
15       A002  R051  02-00-00  05/29/2017  12:00:00  REGULAR   6196666
16       A002  R051  02-00-00  05/29/2017  16:00:00  REGULAR   6196853
17       A002  R051  02-00-00  05/29/2017  20:00:00  REGULAR   6197107
18       A002  R051  02-00-00  05/30/2017  00:00:00  REGULAR   6197230
19       A002  R051  02-00-00  05/30/2017  04:00:00  REGULAR   6197238
20       A002  R051  02-00-00  05/30/2017  08:00:00  REGULAR   6197288
21       A002  R051  02-00-00  05/30/2017  12:00:00  REGULAR   6197470
22       A002  R051  02-00-00  05/30/2017  16:00:00  REGULAR   6197790
23       A002  R051  02-00-00  05/30/2017  20:00:00  REGULAR   6198624
24       A002  R051  02-00-00  05/31/2017  00:00:00  REGULAR   6198819
25       A002  R051  02-00-00  05/31/2017  04:00:00  REGULAR   6198834
26       A002  R051  02-00-00  05/31/2017  08:00:00  REGULAR   6198880
27       A002  R051  02-00-00  05/31/2017  12:00:00  REGULAR   6199053
28       A002  R051  02-00-00  05/31/2017  16:00:00  REGULAR   6199379
29       A002  R051  02-00-00  05/31/2017  20:00:00  REGULAR   6200200
...       ...   ...       ...         ...       ...      ...       ...
785376  TRAM2  R469  00-05-01  06/19/2017  01:00:00  REGULAR      5554
785377  TRAM2  R469  00-05-01  06/19/2017  05:00:00  REGULAR      5554
785378  TRAM2  R469  00-05-01  06/19/2017  09:00:00  REGULAR      5554
785379  TRAM2  R469  00-05-01  06/19/2017  13:00:00  REGULAR      5554
785380  TRAM2  R469  00-05-01  06/19/2017  17:00:00  REGULAR      5554
785381  TRAM2  R469  00-05-01  06/19/2017  21:00:00  REGULAR      5554
785382  TRAM2  R469  00-05-01  06/20/2017  01:00:00  REGULAR      5554
785383  TRAM2  R469  00-05-01  06/20/2017  05:00:00  REGULAR      5554
785384  TRAM2  R469  00-05-01  06/20/2017  09:00:00  REGULAR      5554
785385  TRAM2  R469  00-05-01  06/20/2017  13:00:00  REGULAR      5554
785386  TRAM2  R469  00-05-01  06/20/2017  17:00:00  REGULAR      5554
785387  TRAM2  R469  00-05-01  06/20/2017  21:00:00  REGULAR      5554
785388  TRAM2  R469  00-05-01  06/21/2017  01:00:00  REGULAR      5554
785389  TRAM2  R469  00-05-01  06/21/2017  05:00:00  REGULAR      5554
785390  TRAM2  R469  00-05-01  06/21/2017  09:00:00  REGULAR      5554
785391  TRAM2  R469  00-05-01  06/21/2017  13:00:00  REGULAR      5554
785392  TRAM2  R469  00-05-01  06/21/2017  17:00:00  REGULAR      5554
785393  TRAM2  R469  00-05-01  06/21/2017  21:00:00  REGULAR      5554
785394  TRAM2  R469  00-05-01  06/22/2017  01:00:00  REGULAR      5554
785395  TRAM2  R469  00-05-01  06/22/2017  05:00:00  REGULAR      5554
785396  TRAM2  R469  00-05-01  06/22/2017  09:00:00  REGULAR      5554
785397  TRAM2  R469  00-05-01  06/22/2017  13:00:00  REGULAR      5554
785398  TRAM2  R469  00-05-01  06/22/2017  17:00:00  REGULAR      5554
785399  TRAM2  R469  00-05-01  06/22/2017  21:00:00  REGULAR      5554
785400  TRAM2  R469  00-05-01  06/23/2017  01:00:00  REGULAR      5554
785401  TRAM2  R469  00-05-01  06/23/2017  05:00:00  REGULAR      5554
785402  TRAM2  R469  00-05-01  06/23/2017  09:00:00  REGULAR      5554
785403  TRAM2  R469  00-05-01  06/23/2017  13:00:00  REGULAR      5554
785404  TRAM2  R469  00-05-01  06/23/2017  17:00:00  REGULAR      5554
785405  TRAM2  R469  00-05-01  06/23/2017  21:00:00  REGULAR      5554

         EXITSn  ENTRIESn_hourly  EXITSn_hourly
0       2098317              1.0            1.0
1       2098318             23.0            1.0
2       2098347             16.0           29.0
3       2098432             90.0           85.0
4       2098491            172.0           59.0
5       2098537            247.0           46.0
6       2098559            133.0           22.0
7       2098562             16.0            3.0
8       2098581             16.0           19.0
9       2098646             94.0           65.0
10      2098685            162.0           39.0
11      2098723            260.0           38.0
12      2098745            123.0           22.0
13      2098747             18.0            2.0
14      2098766             10.0           19.0
15      2098845             69.0           79.0
16      2098891            187.0           46.0
17      2098922            254.0           31.0
18      2098946            123.0           24.0
19      2098949              8.0            3.0
20      2099066             50.0          117.0
21      2099345            182.0          279.0
22      2099442            320.0           97.0
23      2099521            834.0           79.0
24      2099552            195.0           31.0
25      2099555             15.0            3.0
26      2099671             46.0          116.0
27      2099950            173.0          279.0
28      2100021            326.0           71.0
29      2100072            821.0           51.0
...         ...              ...            ...
785376      301              0.0            0.0
785377      301              0.0            0.0
785378      301              0.0            0.0
785379      301              0.0            0.0
785380      301              0.0            0.0
785381      301              0.0            0.0
785382      301              0.0            0.0
785383      301              0.0            0.0
785384      301              0.0            0.0
785385      301              0.0            0.0
785386      301              0.0            0.0
785387      301              0.0            0.0
785388      301              0.0            0.0
785389      301              0.0            0.0
785390      301              0.0            0.0
785391      301              0.0            0.0
785392      301              0.0            0.0
785393      301              0.0            0.0
785394      301              0.0            0.0
785395      301              0.0            0.0
785396      301              0.0            0.0
785397      301              0.0            0.0
785398      301              0.0            0.0
785399      301              0.0            0.0
785400      301              0.0            0.0
785401      301              0.0            0.0
785402      301              0.0            0.0
785403      301              0.0            0.0
785404      301              0.0            0.0
785405      301              0.0            0.0

[785406 rows x 10 columns]

### *Exercicio 1.6*

Dado uma variável de entrada que representa o tempo no formato de:
     "00:00:00" (hora: minutos: segundos)
    
Escreva uma função para extrair a parte da hora do tempo variável de entrada
E devolva-o como um número inteiro. Por exemplo:
         
         1) se a hora for 00, seu código deve retornar 0
         2) se a hora for 01, seu código deve retornar 1
         3) se a hora for 21, seu código deve retornar 21
        
Por favor, devolva a hora como um número inteiro.

In [5]:
# coding: utf-8

from datetime import datetime

def time_to_hour(time):
    return datetime.strptime(time, '%H:%M:%S').time().hour
	
print(time_to_hour('21:35:00'))

21

## Exercicio 2 - Análise dos dados

### *Exercicio 2.1*

Para verificar a relação entre o movimento do metrô e o clima, precisaremos complementar os dados do arquivo já baixado com os dados do clima.
Nós complementamos para você este arquivo com os dados de clima de Nova Iorque  e disponibilizamos na área de materiais do projeto. Você pode acessa-lo pelo link: https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/turnstile_data_master_with_weather.csv

Agora que temos nossos dados em um arquivo csv, escreva um código python que leia este arquivo e salve-o em um data frame do pandas. 

Dica: 

Utilize o comando abaixo para ler o arquivo:

```python
pd.read_csv('output_list.txt', sep=",")
```

In [6]:
# coding: utf-8

import pandas as pd

def return_data_frame(filename):

    return pd.read_csv(filename, encoding='ISO-8859-1')

filename = "turnstile_data_master_with_weather.csv"
print(return_data_frame(filename))

        Unnamed: 0  UNIT       DATEn     TIMEn  Hour    DESCn  \
0                0  R001  2011-05-01  01:00:00     1  REGULAR
1                1  R001  2011-05-01  05:00:00     5  REGULAR
2                2  R001  2011-05-01  09:00:00     9  REGULAR
3                3  R001  2011-05-01  13:00:00    13  REGULAR
4                4  R001  2011-05-01  17:00:00    17  REGULAR
5                5  R001  2011-05-01  21:00:00    21  REGULAR
6                6  R002  2011-05-01  01:00:00     1  REGULAR
7                7  R002  2011-05-01  05:00:00     5  REGULAR
8                8  R002  2011-05-01  09:00:00     9  REGULAR
9                9  R002  2011-05-01  13:00:00    13  REGULAR
10              10  R002  2011-05-01  17:00:00    17  REGULAR
11              11  R002  2011-05-01  21:00:00    21  REGULAR
12              12  R003  2011-05-01  00:00:00     0  REGULAR
13              13  R003  2011-05-01  04:00:00     4  REGULAR
14              14  R003  2011-05-01  12:00:00    12  REGULAR
15              15  R003  2011-05-01  16:00:00    16  REGULAR
16              16  R003  2011-05-01  20:00:00    20  REGULAR
17              17  R004  2011-05-01  00:00:00     0  REGULAR
18              18  R004  2011-05-01  04:00:00     4  REGULAR
19              19  R004  2011-05-01  08:00:00     8  REGULAR
20              20  R004  2011-05-01  12:00:00    12  REGULAR
21              21  R004  2011-05-01  16:00:00    16  REGULAR
22              22  R004  2011-05-01  20:00:00    20  REGULAR
23              23  R005  2011-05-01  00:00:00     0  REGULAR
24              24  R005  2011-05-01  04:00:00     4  REGULAR
25              25  R005  2011-05-01  12:00:00    12  REGULAR
26              26  R005  2011-05-01  16:00:00    16  REGULAR
27              27  R005  2011-05-01  20:00:00    20  REGULAR
28              28  R006  2011-05-01  00:00:00     0  REGULAR
29              29  R006  2011-05-01  04:00:00     4  REGULAR
...            ...   ...         ...       ...   ...      ...
131921      131921  R552  2011-05-30  17:55:25    17  REGULAR
131922      131922  R552  2011-05-30  18:09:09    18  REGULAR
131923      131923  R552  2011-05-30  18:15:11    18  REGULAR
131924      131924  R552  2011-05-30  18:27:32    18  REGULAR
131925      131925  R552  2011-05-30  18:46:54    18  REGULAR
131926      131926  R552  2011-05-30  19:09:29    19  REGULAR
131927      131927  R552  2011-05-30  19:11:30    19  REGULAR
131928      131928  R552  2011-05-30  19:16:44    19  REGULAR
131929      131929  R552  2011-05-30  19:23:45    19  REGULAR
131930      131930  R552  2011-05-30  19:36:27    19  REGULAR
131931      131931  R552  2011-05-30  19:38:47    19  REGULAR
131932      131932  R552  2011-05-30  19:52:07    19  REGULAR
131933      131933  R552  2011-05-30  20:10:01    20  REGULAR
131934      131934  R552  2011-05-30  20:17:36    20  REGULAR
131935      131935  R552  2011-05-30  20:23:06    20  REGULAR
131936      131936  R552  2011-05-30  20:51:44    20  REGULAR
131937      131937  R552  2011-05-30  20:58:04    20  REGULAR
131938      131938  R552  2011-05-30  20:58:21    20  REGULAR
131939      131939  R552  2011-05-30  21:14:49    21  REGULAR
131940      131940  R552  2011-05-30  21:21:28    21  REGULAR
131941      131941  R552  2011-05-30  22:07:25    22  REGULAR
131942      131942  R552  2011-05-30  22:21:09    22  REGULAR
131943      131943  R552  2011-05-30  22:27:11    22  REGULAR
131944      131944  R552  2011-05-30  22:39:32    22  REGULAR
131945      131945  R552  2011-05-30  22:58:54    22  REGULAR
131946      131946  R552  2011-05-30  23:21:29    23  REGULAR
131947      131947  R552  2011-05-30  23:23:30    23  REGULAR
131948      131948  R552  2011-05-30  23:28:44    23  REGULAR
131949      131949  R552  2011-05-30  23:35:45    23  REGULAR
131950      131950  R552  2011-05-30  23:50:47    23  REGULAR

        ENTRIESn_hourly  EXITSn_hourly  maxpressurei  maxdewpti   ...     \
0                   0.0            0.0         30.31       42.0   ...
1                 217.0          553.0         30.31       42.0   ...
2                 890.0         1262.0         30.31       42.0   ...
3                2451.0         3708.0         30.31       42.0   ...
4                4400.0         2501.0         30.31       42.0   ...
5                3372.0         2122.0         30.31       42.0   ...
6                   0.0            0.0         30.31       42.0   ...
7                  42.0           66.0         30.31       42.0   ...
8                  50.0          125.0         30.31       42.0   ...
9                 316.0          716.0         30.31       42.0   ...
10                633.0          968.0         30.31       42.0   ...
11                639.0          566.0         30.31       42.0   ...
12                  0.0            0.0         30.31       42.0   ...
13                  0.0            0.0         30.31       42.0   ...
14                  0.0            0.0         30.31       42.0   ...
15                  0.0            0.0         30.31       42.0   ...
16                  0.0            0.0         30.31       42.0   ...
17                  0.0            0.0         30.31       42.0   ...
18                  0.0            0.0         30.31       42.0   ...
19                  0.0            0.0         30.31       42.0   ...
20                  0.0            0.0         30.31       42.0   ...
21                  0.0            0.0         30.31       42.0   ...
22                  0.0            0.0         30.31       42.0   ...
23                  0.0            0.0         30.31       42.0   ...
24                  0.0            2.0         30.31       42.0   ...
25                  0.0            2.0         30.31       42.0   ...
26                  1.0            7.0         30.31       42.0   ...
27                  0.0            0.0         30.31       42.0   ...
28                  0.0            0.0         30.31       42.0   ...
29                  0.0            1.0         30.31       42.0   ...
...                 ...            ...           ...        ...   ...
131921              6.0            2.0         30.13       70.0   ...
131922            192.0           55.0         30.13       70.0   ...
131923            350.0           90.0         30.13       70.0   ...
131924             25.0            3.0         30.13       70.0   ...
131925              0.0            0.0         30.13       70.0   ...
131926             30.0            2.0         30.13       70.0   ...
131927            208.0          998.0         30.13       70.0   ...
131928            107.0          199.0         30.13       70.0   ...
131929            139.0           38.0         30.13       70.0   ...
131930            331.0          399.0         30.13       70.0   ...
131931            275.0           71.0         30.13       70.0   ...
131932            133.0           39.0         30.13       70.0   ...
131933              7.0          332.0         30.13       70.0   ...
131934            128.0          447.0         30.13       70.0   ...
131935            142.0          677.0         30.13       70.0   ...
131936              0.0            0.0         30.13       70.0   ...
131937            248.0          257.0         30.13       70.0   ...
131938             62.0           32.0         30.13       70.0   ...
131939            116.0          726.0         30.13       70.0   ...
131940             68.0          115.0         30.13       70.0   ...
131941              7.0            4.0         30.13       70.0   ...
131942             80.0           63.0         30.13       70.0   ...
131943            195.0          207.0         30.13       70.0   ...
131944             18.0            4.0         30.13       70.0   ...
131945              0.0            0.0         30.13       70.0   ...
131946             19.0           14.0         30.13       70.0   ...
131947            158.0         1022.0         30.13       70.0   ...
131948             54.0          275.0         30.13       70.0   ...
131949             59.0           46.0         30.13       70.0   ...
131950            123.0          108.0         30.13       70.0   ...

        meandewpti  meanpressurei  fog  rain  meanwindspdi  mintempi  \
0             39.0          30.27  0.0   0.0           5.0      50.0
1             39.0          30.27  0.0   0.0           5.0      50.0
2             39.0          30.27  0.0   0.0           5.0      50.0
3             39.0          30.27  0.0   0.0           5.0      50.0
4             39.0          30.27  0.0   0.0           5.0      50.0
5             39.0          30.27  0.0   0.0           5.0      50.0
6             39.0          30.27  0.0   0.0           5.0      50.0
7             39.0          30.27  0.0   0.0           5.0      50.0
8             39.0          30.27  0.0   0.0           5.0      50.0
9             39.0          30.27  0.0   0.0           5.0      50.0
10            39.0          30.27  0.0   0.0           5.0      50.0
11            39.0          30.27  0.0   0.0           5.0      50.0
12            39.0          30.27  0.0   0.0           5.0      50.0
13            39.0          30.27  0.0   0.0           5.0      50.0
14            39.0          30.27  0.0   0.0           5.0      50.0
15            39.0          30.27  0.0   0.0           5.0      50.0
16            39.0          30.27  0.0   0.0           5.0      50.0
17            39.0          30.27  0.0   0.0           5.0      50.0
18            39.0          30.27  0.0   0.0           5.0      50.0
19            39.0          30.27  0.0   0.0           5.0      50.0
20            39.0          30.27  0.0   0.0           5.0      50.0
21            39.0          30.27  0.0   0.0           5.0      50.0
22            39.0          30.27  0.0   0.0           5.0      50.0
23            39.0          30.27  0.0   0.0           5.0      50.0
24            39.0          30.27  0.0   0.0           5.0      50.0
25            39.0          30.27  0.0   0.0           5.0      50.0
26            39.0          30.27  0.0   0.0           5.0      50.0
27            39.0          30.27  0.0   0.0           5.0      50.0
28            39.0          30.27  0.0   0.0           5.0      50.0
29            39.0          30.27  0.0   0.0           5.0      50.0
...            ...            ...  ...   ...           ...       ...
131921        68.0          30.08  0.0   1.0           5.0      70.0
131922        68.0          30.08  0.0   1.0           5.0      70.0
131923        68.0          30.08  0.0   1.0           5.0      70.0
131924        68.0          30.08  0.0   1.0           5.0      70.0
131925        68.0          30.08  0.0   1.0           5.0      70.0
131926        68.0          30.08  0.0   1.0           5.0      70.0
131927        68.0          30.08  0.0   1.0           5.0      70.0
131928        68.0          30.08  0.0   1.0           5.0      70.0
131929        68.0          30.08  0.0   1.0           5.0      70.0
131930        68.0          30.08  0.0   1.0           5.0      70.0
131931        68.0          30.08  0.0   1.0           5.0      70.0
131932        68.0          30.08  0.0   1.0           5.0      70.0
131933        68.0          30.08  0.0   1.0           5.0      70.0
131934        68.0          30.08  0.0   1.0           5.0      70.0
131935        68.0          30.08  0.0   1.0           5.0      70.0
131936        68.0          30.08  0.0   1.0           5.0      70.0
131937        68.0          30.08  0.0   1.0           5.0      70.0
131938        68.0          30.08  0.0   1.0           5.0      70.0
131939        68.0          30.08  0.0   1.0           5.0      70.0
131940        68.0          30.08  0.0   1.0           5.0      70.0
131941        68.0          30.08  0.0   1.0           5.0      70.0
131942        68.0          30.08  0.0   1.0           5.0      70.0
131943        68.0          30.08  0.0   1.0           5.0      70.0
131944        68.0          30.08  0.0   1.0           5.0      70.0
131945        68.0          30.08  0.0   1.0           5.0      70.0
131946        68.0          30.08  0.0   1.0           5.0      70.0
131947        68.0          30.08  0.0   1.0           5.0      70.0
131948        68.0          30.08  0.0   1.0           5.0      70.0
131949        68.0          30.08  0.0   1.0           5.0      70.0
131950        68.0          30.08  0.0   1.0           5.0      70.0

        meantempi  maxtempi  precipi  thunder
0            60.0      69.0     0.00      0.0
1            60.0      69.0     0.00      0.0
2            60.0      69.0     0.00      0.0
3            60.0      69.0     0.00      0.0
4            60.0      69.0     0.00      0.0
5            60.0      69.0     0.00      0.0
6            60.0      69.0     0.00      0.0
7            60.0      69.0     0.00      0.0
8            60.0      69.0     0.00      0.0
9            60.0      69.0     0.00      0.0
10           60.0      69.0     0.00      0.0
11           60.0      69.0     0.00      0.0
12           60.0      69.0     0.00      0.0
13           60.0      69.0     0.00      0.0
14           60.0      69.0     0.00      0.0
15           60.0      69.0     0.00      0.0
16           60.0      69.0     0.00      0.0
17           60.0      69.0     0.00      0.0
18           60.0      69.0     0.00      0.0
19           60.0      69.0     0.00      0.0
20           60.0      69.0     0.00      0.0
21           60.0      69.0     0.00      0.0
22           60.0      69.0     0.00      0.0
23           60.0      69.0     0.00      0.0
24           60.0      69.0     0.00      0.0
25           60.0      69.0     0.00      0.0
26           60.0      69.0     0.00      0.0
27           60.0      69.0     0.00      0.0
28           60.0      69.0     0.00      0.0
29           60.0      69.0     0.00      0.0
...           ...       ...      ...      ...
131921       78.0      86.0     0.29      0.0
131922       78.0      86.0     0.29      0.0
131923       78.0      86.0     0.29      0.0
131924       78.0      86.0     0.29      0.0
131925       78.0      86.0     0.29      0.0
131926       78.0      86.0     0.29      0.0
131927       78.0      86.0     0.29      0.0
131928       78.0      86.0     0.29      0.0
131929       78.0      86.0     0.29      0.0
131930       78.0      86.0     0.29      0.0
131931       78.0      86.0     0.29      0.0
131932       78.0      86.0     0.29      0.0
131933       78.0      86.0     0.29      0.0
131934       78.0      86.0     0.29      0.0
131935       78.0      86.0     0.29      0.0
131936       78.0      86.0     0.29      0.0
131937       78.0      86.0     0.29      0.0
131938       78.0      86.0     0.29      0.0
131939       78.0      86.0     0.29      0.0
131940       78.0      86.0     0.29      0.0
131941       78.0      86.0     0.29      0.0
131942       78.0      86.0     0.29      0.0
131943       78.0      86.0     0.29      0.0
131944       78.0      86.0     0.29      0.0
131945       78.0      86.0     0.29      0.0
131946       78.0      86.0     0.29      0.0
131947       78.0      86.0     0.29      0.0
131948       78.0      86.0     0.29      0.0
131949       78.0      86.0     0.29      0.0
131950       78.0      86.0     0.29      0.0

[131951 rows x 22 columns]

### *Exercicio 2.2*

Agora crie uma função que calcule a quantidade de dias chuvosos, para isso retorne a contagem do numero de dias onde a coluna *"rain"* é igual a 1.

Dica: Você também pode achar que a interpretação de números como números inteiros ou float pode não
     funcionar inicialmente. Para contornar esta questão, pode ser útil converter
     esses números para números inteiros. Isso pode ser feito escrevendo cast (coluna como inteiro).
     Então, por exemplo, se queríamos lançar a coluna maxtempi como um número inteiro, nós devemos
     escrever algo como cast (maxtempi as integer) = 76, em oposição a simplesmente
     onde maxtempi = 76.

In [7]:
# coding: utf-8

import pandas as pd
import pandasql

def return_data_frame(filename):

    return pd.read_csv(filename, encoding='ISO-8859-1')

def num_rainy_days(df):
    q = """
    select * from df where rain >= 1 ;
    """
    return pandasql.sqldf(q, locals())
	
filename = "turnstile_data_master_with_weather.csv"
df = return_data_frame(filename)
print(num_rainy_days(df))

       Unnamed: 0  UNIT       DATEn     TIMEn  Hour    DESCn  ENTRIESn_hourly  \
0           13337  R001  2011-05-04  01:00:00     1  REGULAR           1132.0
1           13338  R001  2011-05-04  05:00:00     5  REGULAR            164.0
2           13339  R001  2011-05-04  07:20:01     7  REGULAR            647.0
3           13340  R001  2011-05-04  09:00:00     9  REGULAR           6468.0
4           13341  R001  2011-05-04  13:00:00    13  REGULAR           4683.0
5           13342  R001  2011-05-04  17:00:00    17  REGULAR           6243.0
6           13343  R001  2011-05-04  21:00:00    21  REGULAR           8448.0
7           13344  R002  2011-05-04  01:00:00     1  REGULAR            444.0
8           13345  R002  2011-05-04  05:00:00     5  REGULAR             26.0
9           13346  R002  2011-05-04  09:00:00     9  REGULAR            318.0
10          13347  R002  2011-05-04  13:00:00    13  REGULAR            955.0
11          13348  R002  2011-05-04  17:00:00    17  REGULAR           2546.0
12          13349  R002  2011-05-04  21:00:00    21  REGULAR           4038.0
13          13350  R003  2011-05-04  00:00:00     0  REGULAR             83.0
14          13351  R003  2011-05-04  04:00:00     4  REGULAR             24.0
15          13352  R003  2011-05-04  08:00:00     8  REGULAR            532.0
16          13353  R003  2011-05-04  12:00:00    12  REGULAR            454.0
17          13354  R003  2011-05-04  16:00:00    16  REGULAR            247.0
18          13355  R003  2011-05-04  20:00:00    20  REGULAR            220.0
19          13356  R004  2011-05-04  00:00:00     0  REGULAR            162.0
20          13357  R004  2011-05-04  04:00:00     4  REGULAR             34.0
21          13358  R004  2011-05-04  11:28:40    11  REGULAR            745.0
22          13359  R004  2011-05-04  11:50:02    11  REGULAR            388.0
23          13360  R004  2011-05-04  12:00:00    12  REGULAR           1171.0
24          13361  R004  2011-05-04  20:00:00    20  REGULAR            892.0
25          13362  R005  2011-05-04  00:00:00     0  REGULAR            178.0
26          13363  R005  2011-05-04  04:00:00     4  REGULAR             37.0
27          13364  R005  2011-05-04  12:00:00    12  REGULAR           2636.0
28          13365  R005  2011-05-04  16:00:00    16  REGULAR            569.0
29          13366  R005  2011-05-04  20:00:00    20  REGULAR            406.0
...           ...   ...         ...       ...   ...      ...              ...
44074      131921  R552  2011-05-30  17:55:25    17  REGULAR              6.0
44075      131922  R552  2011-05-30  18:09:09    18  REGULAR            192.0
44076      131923  R552  2011-05-30  18:15:11    18  REGULAR            350.0
44077      131924  R552  2011-05-30  18:27:32    18  REGULAR             25.0
44078      131925  R552  2011-05-30  18:46:54    18  REGULAR              0.0
44079      131926  R552  2011-05-30  19:09:29    19  REGULAR             30.0
44080      131927  R552  2011-05-30  19:11:30    19  REGULAR            208.0
44081      131928  R552  2011-05-30  19:16:44    19  REGULAR            107.0
44082      131929  R552  2011-05-30  19:23:45    19  REGULAR            139.0
44083      131930  R552  2011-05-30  19:36:27    19  REGULAR            331.0
44084      131931  R552  2011-05-30  19:38:47    19  REGULAR            275.0
44085      131932  R552  2011-05-30  19:52:07    19  REGULAR            133.0
44086      131933  R552  2011-05-30  20:10:01    20  REGULAR              7.0
44087      131934  R552  2011-05-30  20:17:36    20  REGULAR            128.0
44088      131935  R552  2011-05-30  20:23:06    20  REGULAR            142.0
44089      131936  R552  2011-05-30  20:51:44    20  REGULAR              0.0
44090      131937  R552  2011-05-30  20:58:04    20  REGULAR            248.0
44091      131938  R552  2011-05-30  20:58:21    20  REGULAR             62.0
44092      131939  R552  2011-05-30  21:14:49    21  REGULAR            116.0
44093      131940  R552  2011-05-30  21:21:28    21  REGULAR             68.0
44094      131941  R552  2011-05-30  22:07:25    22  REGULAR              7.0
44095      131942  R552  2011-05-30  22:21:09    22  REGULAR             80.0
44096      131943  R552  2011-05-30  22:27:11    22  REGULAR            195.0
44097      131944  R552  2011-05-30  22:39:32    22  REGULAR             18.0
44098      131945  R552  2011-05-30  22:58:54    22  REGULAR              0.0
44099      131946  R552  2011-05-30  23:21:29    23  REGULAR             19.0
44100      131947  R552  2011-05-30  23:23:30    23  REGULAR            158.0
44101      131948  R552  2011-05-30  23:28:44    23  REGULAR             54.0
44102      131949  R552  2011-05-30  23:35:45    23  REGULAR             59.0
44103      131950  R552  2011-05-30  23:50:47    23  REGULAR            123.0

       EXITSn_hourly  maxpressurei  maxdewpti   ...     meandewpti  \
0             1840.0         30.03       57.0   ...           48.0
1              305.0         30.03       57.0   ...           48.0
2              425.0         30.03       57.0   ...           48.0
3             6293.0         30.03       57.0   ...           48.0
4             6226.0         30.03       57.0   ...           48.0
5             4940.0         30.03       57.0   ...           48.0
6             5918.0         30.03       57.0   ...           48.0
7              177.0         30.03       57.0   ...           48.0
8               57.0         30.03       57.0   ...           48.0
9             2286.0         30.03       57.0   ...           48.0
10            2254.0         30.03       57.0   ...           48.0
11            1293.0         30.03       57.0   ...           48.0
12             679.0         30.03       57.0   ...           48.0
13             174.0         30.03       57.0   ...           48.0
14              35.0         30.03       57.0   ...           48.0
15             130.0         30.03       57.0   ...           48.0
16             107.0         30.03       57.0   ...           48.0
17             249.0         30.03       57.0   ...           48.0
18             356.0         30.03       57.0   ...           48.0
19             423.0         30.03       57.0   ...           48.0
20             113.0         30.03       57.0   ...           48.0
21             226.0         30.03       57.0   ...           48.0
22             168.0         30.03       57.0   ...           48.0
23             383.0         30.03       57.0   ...           48.0
24            1069.0         30.03       57.0   ...           48.0
25             567.0         30.03       57.0   ...           48.0
26             116.0         30.03       57.0   ...           48.0
27             436.0         30.03       57.0   ...           48.0
28             672.0         30.03       57.0   ...           48.0
29            1206.0         30.03       57.0   ...           48.0
...              ...           ...        ...   ...            ...
44074            2.0         30.13       70.0   ...           68.0
44075           55.0         30.13       70.0   ...           68.0
44076           90.0         30.13       70.0   ...           68.0
44077            3.0         30.13       70.0   ...           68.0
44078            0.0         30.13       70.0   ...           68.0
44079            2.0         30.13       70.0   ...           68.0
44080          998.0         30.13       70.0   ...           68.0
44081          199.0         30.13       70.0   ...           68.0
44082           38.0         30.13       70.0   ...           68.0
44083          399.0         30.13       70.0   ...           68.0
44084           71.0         30.13       70.0   ...           68.0
44085           39.0         30.13       70.0   ...           68.0
44086          332.0         30.13       70.0   ...           68.0
44087          447.0         30.13       70.0   ...           68.0
44088          677.0         30.13       70.0   ...           68.0
44089            0.0         30.13       70.0   ...           68.0
44090          257.0         30.13       70.0   ...           68.0
44091           32.0         30.13       70.0   ...           68.0
44092          726.0         30.13       70.0   ...           68.0
44093          115.0         30.13       70.0   ...           68.0
44094            4.0         30.13       70.0   ...           68.0
44095           63.0         30.13       70.0   ...           68.0
44096          207.0         30.13       70.0   ...           68.0
44097            4.0         30.13       70.0   ...           68.0
44098            0.0         30.13       70.0   ...           68.0
44099           14.0         30.13       70.0   ...           68.0
44100         1022.0         30.13       70.0   ...           68.0
44101          275.0         30.13       70.0   ...           68.0
44102           46.0         30.13       70.0   ...           68.0
44103          108.0         30.13       70.0   ...           68.0

       meanpressurei  fog  rain  meanwindspdi  mintempi  meantempi  maxtempi  \
0              29.97  0.0   1.0           6.0      46.0       55.0      64.0
1              29.97  0.0   1.0           6.0      46.0       55.0      64.0
2              29.97  0.0   1.0           6.0      46.0       55.0      64.0
3              29.97  0.0   1.0           6.0      46.0       55.0      64.0
4              29.97  0.0   1.0           6.0      46.0       55.0      64.0
5              29.97  0.0   1.0           6.0      46.0       55.0      64.0
6              29.97  0.0   1.0           6.0      46.0       55.0      64.0
7              29.97  0.0   1.0           6.0      46.0       55.0      64.0
8              29.97  0.0   1.0           6.0      46.0       55.0      64.0
9              29.97  0.0   1.0           6.0      46.0       55.0      64.0
10             29.97  0.0   1.0           6.0      46.0       55.0      64.0
11             29.97  0.0   1.0           6.0      46.0       55.0      64.0
12             29.97  0.0   1.0           6.0      46.0       55.0      64.0
13             29.97  0.0   1.0           6.0      46.0       55.0      64.0
14             29.97  0.0   1.0           6.0      46.0       55.0      64.0
15             29.97  0.0   1.0           6.0      46.0       55.0      64.0
16             29.97  0.0   1.0           6.0      46.0       55.0      64.0
17             29.97  0.0   1.0           6.0      46.0       55.0      64.0
18             29.97  0.0   1.0           6.0      46.0       55.0      64.0
19             29.97  0.0   1.0           6.0      46.0       55.0      64.0
20             29.97  0.0   1.0           6.0      46.0       55.0      64.0
21             29.97  0.0   1.0           6.0      46.0       55.0      64.0
22             29.97  0.0   1.0           6.0      46.0       55.0      64.0
23             29.97  0.0   1.0           6.0      46.0       55.0      64.0
24             29.97  0.0   1.0           6.0      46.0       55.0      64.0
25             29.97  0.0   1.0           6.0      46.0       55.0      64.0
26             29.97  0.0   1.0           6.0      46.0       55.0      64.0
27             29.97  0.0   1.0           6.0      46.0       55.0      64.0
28             29.97  0.0   1.0           6.0      46.0       55.0      64.0
29             29.97  0.0   1.0           6.0      46.0       55.0      64.0
...              ...  ...   ...           ...       ...        ...       ...
44074          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44075          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44076          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44077          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44078          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44079          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44080          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44081          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44082          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44083          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44084          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44085          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44086          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44087          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44088          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44089          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44090          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44091          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44092          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44093          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44094          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44095          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44096          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44097          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44098          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44099          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44100          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44101          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44102          30.08  0.0   1.0           5.0      70.0       78.0      86.0
44103          30.08  0.0   1.0           5.0      70.0       78.0      86.0

       precipi  thunder
0         0.50      0.0
1         0.50      0.0
2         0.50      0.0
3         0.50      0.0
4         0.50      0.0
5         0.50      0.0
6         0.50      0.0
7         0.50      0.0
8         0.50      0.0
9         0.50      0.0
10        0.50      0.0
11        0.50      0.0
12        0.50      0.0
13        0.50      0.0
14        0.50      0.0
15        0.50      0.0
16        0.50      0.0
17        0.50      0.0
18        0.50      0.0
19        0.50      0.0
20        0.50      0.0
21        0.50      0.0
22        0.50      0.0
23        0.50      0.0
24        0.50      0.0
25        0.50      0.0
26        0.50      0.0
27        0.50      0.0
28        0.50      0.0
29        0.50      0.0
...        ...      ...
44074     0.29      0.0
44075     0.29      0.0
44076     0.29      0.0
44077     0.29      0.0
44078     0.29      0.0
44079     0.29      0.0
44080     0.29      0.0
44081     0.29      0.0
44082     0.29      0.0
44083     0.29      0.0
44084     0.29      0.0
44085     0.29      0.0
44086     0.29      0.0
44087     0.29      0.0
44088     0.29      0.0
44089     0.29      0.0
44090     0.29      0.0
44091     0.29      0.0
44092     0.29      0.0
44093     0.29      0.0
44094     0.29      0.0
44095     0.29      0.0
44096     0.29      0.0
44097     0.29      0.0
44098     0.29      0.0
44099     0.29      0.0
44100     0.29      0.0
44101     0.29      0.0
44102     0.29      0.0
44103     0.29      0.0

[44104 rows x 22 columns]

### *Exercicio 2.3*

Calcule se estava nebuloso ou não (0 ou 1) e a temperatura máxima para fog (isto é, a temperatura máxima 
     para dias nebulosos e não nebuloso).

In [8]:

def max_temp_aggregate_by_fog(df):
    
    #your code here 
    return

### *Exercicio 2.4

Calcule agora a média de 'meantempi' nos dias que são sábado ou domingo (finais de semana):

In [ ]:
def avg_weekend_temperature(filename):
  
    mean_temp_weekends = 
    
    return mean_temp_weekends

### *Exercicio 2.5

Calcule a média da temperatura mínima 'mintempi' nos dias chuvosos onde da temperatura mínima foi maior que do 55 graus:

In [ ]:
def avg_min_temperature(filename):

    avg_min_temp_rainy = 
    
    return avg_min_temp_rainy

### *Exercicio 2.6

Antes de realizar qualquer análise, pode ser útil olhar para os dados que esperamos analisar. Mais especificamente, vamos examinR as entradas por hora em nossos dados do metrô de Nova York para determinar a distribuição dos dados. Estes dados são armazenados na coluna ['ENTRIESn_hourly'].
    
Trace dois histogramas nos mesmos eixos para mostrar as entradas quando esta chovendo vs quando não está chovendo. 
Abaixo está um exemplo sobre como traçar histogramas com pandas e matplotlib:
     
```python
Turnstile_weather ['column_to_graph']. Hist ()
```

In [ ]:
import numpy as np
import pandas
import matplotlib.pyplot as plt

def entries_histogram(turnstile_weather):
    
    
    
    plt.figure()
    turnstile_weather['...'] # your code here to plot a historgram for hourly entries when it is raining
    turnstile_weather['...'] # your code here to plot a histogram for hourly entries when it is not raining
    return plt

### *Exercicio 2.7

Os dados que acabou de plotar que tipo de ditribuição? Existe diferença na distribuição entre dias chuvosos e não chuvosos?

** Resposta **: Substitua este texto pela sua resposta!

### *Exercicio 2.8

Construa uma função que que retorne:

1. A média das entradas com chuva
2. A média das entradas sem chuva
3. O p-value comparando o numero com chuva e o número sem chuva

In [ ]:
import numpy as np
import scipy
import scipy.stats
import pandas

def mann_whitney_plus_means(turnstile_weather):
    
    
    ### YOUR CODE HERE ###
    
    return with_rain_mean, without_rain_mean, p # leave this line for the grader

Responda as perguntas abaixo de acordo com a saida das suas funções:

1. Qual a média das entradas com chuva?
2. Qual a média das entradas sem chuva?
3. Qual o p-value comparando os numeros com chuva e sem chuva?

** Resposta **: Substitua este texto pela sua resposta!

## Exercicio 3 - Map Reduce

### *Exercicio 3.1*

A entrada para esse exercício e o mesmo arquivo da seção anterior (Exercicio 2). Você pode baixar o arquivo neste link:

 https://s3.amazonaws.com/content.udacity-data.com/courses/ud359/turnstile_data_master_with_weather.csv

Varmos criar um mapeador agora. Para cada linha de entrada, a saída do mapeador deve IMPRIMIR (não retornar) a UNIT como uma chave e o número de ENTRIESn_hourly como o valor. Separe a chave e o valor por uma guia. Por exemplo: 'R002 \ t105105.0'

In [ ]:
import sys

def mapper():
    

    for line in sys.stdin:
        # your code here


mapper()

### *Exercicio 3.2*

Agora crie o redutor. Dado o resultado do mapeador do exercicio anterior, o redutor deve imprimir(Não retornar) uma linha por UNIT, juntamente com o número total de ENTRIESn_hourly.Ao longo de maio (que é a duração dos nossos dados), separados por uma guia. Um exemplo de linha de saída do redutor pode ser assim: 'R001 \ t500625.0'

Você pode assumir que a entrada para o redutor está ordenada de tal forma que todas as linhas correspondentes a uma unidade particular são agrupados.

In [ ]:
def reducer():
    

    for line in sys.stdin:
        # your code here

        
reducer()